#!/bin/bash

./script/install 1>/dev/null 2>&1

git_hash=`git log -1 --pretty=%h`

todo_count=`grep -ri TODO --include="*.rb" . | wc -l`

test_results=`rspec . -f StatisticsFormatter`

git_log=`git log -1 --pretty=%ae,%f`

echo "$git_hash,$todo_count,$test_results,$git_log"
