#!/bin/bash

./script/install 1>/dev/null 2>&1

git_hash=`git log -1 --pretty=%h`

todo_count=`grep -ri TODO --include="*.rb" . | wc -l`

prod_lines=`find lib -iname "*.rb" | xargs cat | wc -l`
spec_lines=`find spec -iname "*.rb" | xargs cat | wc -l`

test_results=`rspec . -f StatisticsFormatter`

echo "$git_hash,$todo_count,$prod_lines,$spec_lines,$test_results"
